name: Update search index
on:
  push:
    branches:
      - main

jobs:
  run:
    name: Update search index
    if: ${{ github.repository == 'qunitjs/qunit' }} # skip on forks, needs secret
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: docs/
          ruby-version: 2.7
          bundler-cache: true

      - run: bundle exec jekyll algolia
        working-directory: docs/
        env:
          ALGOLIA_API_KEY: "${{ secrets.ALGOLIA_API_KEY }}"
