name: spider-check
on:
  # Once a week on Friday at 00:00
  schedule:
    - cron: '0 0 * * 5'
  # Or manually
  workflow_dispatch:
  # Or when developing this workflow
  push:
    paths:
      - .github/workflows/spider-check.yaml
  pull_request:
    paths:
      - .github/workflows/spider-check.yaml

jobs:
  spider-check:
    if: ${{ github.repository_owner == 'qunitjs' }} # skip on forks
    runs-on: ubuntu-latest
    env:
      # Site address to crawl
      #
      # Example:
      # - https://example.org
      # - https://example.github.io/
      # - https://example.github.io/my-project/
      MY_SITE: https://api.qunitjs.com
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install hydra
        uses: actions/checkout@v3
        with:
          repository: jquery/hydra-link-checker
          ref: v2.0.0
          path: hydra

      - name: Run hydra-link-checker
        run: python3 hydra/hydra.py "$MY_SITE" --config build/hydra-config.json
